# Generated by Django 4.1.1 on 2022-11-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study_buddy_app", "0002_class_profile_classes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="classes", new_name="Class",
        ),
    ]
