# Generated by Django 4.1.1 on 2022-11-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_buddy_app", "0003_rename_classes_profile_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="Class",
            field=models.ManyToManyField(blank=True, to="study_buddy_app.class"),
        ),
    ]
