# Generated by Django 4.1.1 on 2022-11-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy_app', '0005_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
